site_name: Ocean4DVarNet Contributions Documentation
site_url: https://cia-oceanix.github.io/ocean4dvarnet-contrib/
repo_url: https://github.com/CIA-Oceanix/ocean4dvarnet-contrib/
copyright: "Copyright &copy; IMT Atlantique/OceaniX. This software is governed by the CeCILL-C license under French law and abiding by the rules of distribution of free software."

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.annotate
    - search.suggest
    - search.highlight

plugins:
  - search
  #- dotenv
  - mkdocstrings:
      handlers:
        python:
          paths: ["contrib", "."]
          options:
            show_source: true
            docstring_style: google
            
  # - gen-files:
  #     scripts:
  #       - scripts/generate_contrib_docs.py

nav:
  - Home: index.md
  - Contributions: contrib/index.md
  - Tools: scripts/index.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.details
  - attr_list
  - md_in_html
